server:
  port: 28900

spring:
  application:
    name: autocode   # 服务名

  cloud:
    # nacos 配置中心
    nacos:
      config:
        group: dev
        server-addr: 127.0.0.1:8848
        namespace: c20445c9-9c01-4cc6-ab19-8a9ea0208bbb
        file-extension: yaml
      discovery:
        server-addr: 127.0.0.1:8848
        namespace: c20445c9-9c01-4cc6-ab19-8a9ea0208bbb
  # nacos 配置导入
  config:
    import:
      - nacos:db.yml?group=dev&namespace=c20445c9-9c01-4cc6-ab19-8a9ea0208bbb
      - nacos:redis.yml?group=dev&namespace=c20445c9-9c01-4cc6-ab19-8a9ea0208bbb



mybatis-plus:
  # Mapper.xml 文件位置 Maven 多模块项目的扫描路径需以 classpath*: 开头
  mapperLocations: classpath*:com/**/xml/*Mapper.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl   #用于控制台打印sql语句
  global-config:
    db-config:
      update-strategy: ignored